### ISSUE TITLE
Can't parse the testcase!

### ISSUE THREAD

**Issue by friddle** [glacjay/tiger-c#1]
Error Message:
tiger: ~/frame-mips.c:85: int fr_offset(fr_access_t): Assertion `access && access->kind == FR_IN_FRAME' failed.

stack:
->fr_offset
-->tr_simple_var
--->trans_simple_var
---->trans_var
----->trans_var_Expr
......

environment:
Ubuntu 12.10

please forgive my poor english.

I am new to Compiler Analysis,but your tiger-c is best project of Tiger Compiler of Github.
Please fix this bug.

just found that .SimpleVar should be in FR_IN_FRAME but be the FR_IN_REG.
so compiler return the error

**Comment by glacjay** [comment]
Sorry about the delay. I will find some free time to continue this project, maybe :-) Sorry about that.

**Comment by friddle** [comment]
thanks!

**Comment by glacjay** [comment]
@friddle So, I've finally fixed this particular bug :-)
